### PR TITLE
Fix #14 where the plugin is incorrectly replacing a prefix of another unrelated package

### LINKED ISSUE #14: Deduplication plugin deduping wrong and breaking the webpack build
```
ERROR in /buildeng/bamboo-agent-home/xml-data/build-dir/CONFMICRO-CFCPB10727-BUILDBRANCH/node_modules/@atlassian/ptc-embeddable-directory/dist/components/TeamElement/TeamElement.js
build	18-Nov-2020 00:54:13	(@atlassian/confluence-frontend-server) $ yarn run -s bundle Module not found: Error: Can't resolve '/buildeng/bamboo-agent-home/xml-data/build-dir/CONFMICRO-CFCPB10727-BUILDBRANCH/node_modules/@atlaskit/avatar-group/node_modules/@atlaskit/avatar-group/dist/esm/index.js' in '/buildeng/bamboo-agent-home/xml-data/build-dir/CONFMICRO-CFCPB10727-BUILDBRANCH/node_modules/@atlassian/ptc-embeddable-directory/dist/components/TeamElement'
```

Grep result for the yarn.lock:
```
mdejongh|~/Projects/Atlassian/confluence-frontend on atlaskit-branch-deploy-AFP-2529-qa-branch
± grep 'avatar-group' yarn.lock
    "@atlaskit/avatar-group" "^8.0.0"
"@atlaskit/avatar-group@^7.0.1":
  resolved "https://packages.atlassian.com/api/npm/npm-remote/@atlaskit/avatar-group/-/avatar-group-7.0.1.tgz#5fde6f9863b9819631cc2903b5d1a3dab4498c25"
"@atlaskit/avatar-group@^8.0.0", "@atlaskit/avatar-group@^8.0.11":
  resolved "https://packages.atlassian.com/api/npm/npm-remote/@atlaskit/avatar-group/-/avatar-group-8.0.11.tgz#09893376b91386aed05c17b82cfcb5548bf694a9"
    "@atlaskit/avatar-group" "^8.0.0"
    "@atlaskit/avatar-group" "^8.0.0"
    "@atlaskit/avatar-group" "^8.0.0"
    "@atlaskit/avatar-group" "^8.0.0"
    "@atlaskit/avatar-group" "^8.0.0"
    "@atlaskit/avatar-group" "^7.0.1"
mdejongh@C02XP02SJGH7|~/Projects/Atlassian/confluence-frontend on atlaskit-branch-deploy-AFP-2529-qa-branch
±
```
The majority of the app depends on `avatar-group@8.0.0` but dependency `@atlassian/ptc-embeddable-directory` wants `avatar-group@^7.0.1`.

### PR DESCRIPTION
**Pull request by randing89**
The plugin was incorrectly replacing the prefix of `node_modules/@atlassian/ptc-embeddable-directory/node_modules/@atlaskit/avatar-group/dist/cjs/index.d.ts` when deduplicating `node_modules/@atlassian/ptc-embeddable-directory/node_modules/@atlaskit/avatar`

### CODE REVIEW

**Comment by theKashey** [comment]
#12 would resolve #14 as well - word trie cannot make such mistake by definition.

File: src/index.js [hunk 1]
```diff
@@ -76,7 +76,7 @@ const containsNodeModules = (resolvedResource) => {
 };
 
 const findDuplicate = (res) => (t) => {
-    return res.includes(t);
+    return res.includes(t + '/');
```
Comment (internetofsteve) [inline src/index.js:79]: What are your thoughts on a small comment description here as well as using `path.sep` to allow for unix/windows OS?

```suggestion
     // prevent partial name matches. I.e. don't match `/button` when resolving `/button-group`
    const duplicateDir = `${duplicate}${path.sep}`;
    return resolvedResource.includes(duplicateDir);
```

File: src/__tests__/index.test.js [hunk 2]
```diff
@@ -69,6 +69,48 @@ describe('duplicate-transitive-replacement', () => {
         );
     });
 
+    it('should not mistakenly replace prefix string', () => {
```
Comment (internetofsteve) [inline src/__tests__/index.test.js:72]: This is great, thanks for adding some test coverage for the change. I made a few edits to try and make the code a bit more like a real world example, using hypothetical `radio-button` and `radio-button-group` packages. The test is exactly the same in terms of functionality, what do you think?

```suggestion
    it('should not deduplicate when package name is partial match', () => {
        mockFs({
            [path.resolve(
                'node_modules/@org/component-a/node_modules/@org/radio-button',
                './index.js'
            )]: 'some radio button code',

            [path.resolve(
                'node_modules/@org/component-b/node_modules/@org/radio-button',
                './index.js'
            )]: 'some radio button code',

            [path.resolve(
                'node_modules/@org/component-b/node_modules/@org/radio-button-group',
                './index.js'
            )]: 'some radio button GROUP code',
        });

        const duplicates = [
            // although duplicate packages are prefixed with 'radio-button', these should
            // be ignored as they are not a full match on the 'radio-button-group'
            [
                'node_modules/@org/component-a/node_modules/@org/radio-button',
                'node_modules/@org/component-b/node_modules/@org/radio-button',
            ],
        ];

        const matchingResource = mockResource({
            filename: './index.js',
            context: path.resolve(
                'node_modules/@org/component-b/node_modules/@org/radio-button-group'
            ),
        });

        silent.mockImplementation(() =>
            path.resolve(matchingResource.context, matchingResource.request)
        );

        const finder = require('find-package-json');

        finder.mockImplementation(() => ({
            next: () => ({ value: { name: '@org/component-b' } }),
        }));

        const res = deduplicate(matchingResource, duplicates);

        expect(res).toBeFalsy();
    });
```

File: package.json [hunk 3]
```diff
@@ -27,6 +27,9 @@
     "build:js": "babel src --out-dir build --extensions \".ts,.tsx,.js\" --ignore src/__tests__ --source-maps inline",
     "lint": "eslint --ext .ts,.tsx,.js src/"
   },
+  "jest": {
```
Comment (internetofsteve) [inline package.json:30]: nice!

**Review by internetofsteve — APPROVED** [review]
